name: car_rental
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.1.4
  google_fonts: 2.1.0
  step_progress_indicator: 1.0.0
  line_icons: 2.0.1
  bubble_bottom_bar: 1.2.0
  badges: 2.0.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_launcher_icons: 0.9.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

flutter_icons: 
  android: launcher_icon
  image_path: assets/icon/icon.png
  ios: true

